-- ============================================================
-- Credit Card Fraud Detection System — Supabase Schema
-- Run this in Supabase SQL Editor to recreate all tables
-- ============================================================

-- Drop existing tables (safe to run on fresh project)
DROP TABLE IF EXISTS daily_summary;
DROP TABLE IF EXISTS fraud_alerts;
DROP TABLE IF EXISTS transactions;

-- ============================================================
-- TABLE 1: transactions
-- All scored transactions generated by the Azure Function
-- simulator. Every 5-minute run inserts 15 rows here.
-- ============================================================
CREATE TABLE transactions (
    id                   SERIAL PRIMARY KEY,
    transaction_id       BIGINT,
    transaction_amt      FLOAT,
    product_cd           VARCHAR(10),
    card_type            VARCHAR(20),
    merchant_category    VARCHAR(50),
    transaction_hour     FLOAT,
    fraud_probability    FLOAT,
    is_flagged           BOOLEAN,
    actual_fraud_pattern BOOLEAN,
    recorded_at          TIMESTAMP DEFAULT NOW()
);

-- Index for time-based queries (Power BI filtering by date)
CREATE INDEX idx_transactions_recorded_at ON transactions(recorded_at DESC);

-- Index for fraud filtering
CREATE INDEX idx_transactions_is_flagged ON transactions(is_flagged);

-- ============================================================
-- TABLE 2: fraud_alerts
-- Only flagged transactions, with SHAP-based reason text.
-- Inserted by Azure Function when fraud_probability >= 0.07
-- ============================================================
CREATE TABLE fraud_alerts (
    id                SERIAL PRIMARY KEY,
    transaction_id    BIGINT,
    transaction_amt   FLOAT,
    fraud_probability FLOAT,
    merchant_category VARCHAR(50),
    top_reason        VARCHAR(200),
    alert_status      VARCHAR(20) DEFAULT 'New',
    recorded_at       TIMESTAMP DEFAULT NOW()
);

-- Index for time-based queries
CREATE INDEX idx_fraud_alerts_recorded_at ON fraud_alerts(recorded_at DESC);

-- ============================================================
-- TABLE 3: daily_summary
-- Aggregated stats per day. Updated by Azure Function each run.
-- One row per calendar day (old row deleted and replaced).
-- ============================================================
CREATE TABLE daily_summary (
    id                      SERIAL PRIMARY KEY,
    summary_date            DATE DEFAULT CURRENT_DATE,
    total_transactions      INT,
    total_flagged           INT,
    fraud_rate              FLOAT,
    avg_fraud_probability   FLOAT,
    estimated_savings       FLOAT,
    updated_at              TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- VERIFICATION QUERIES
-- Run these after setup to confirm tables exist
-- ============================================================
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
-- SELECT COUNT(*) FROM transactions;
-- SELECT COUNT(*) FROM fraud_alerts;
-- SELECT * FROM daily_summary ORDER BY updated_at DESC LIMIT 5;
